import './core/jquery'
import './core/bootstrap'
import './core/plugins'
import './core/globals'

import './features/ajax'
import './features/password'
import './features/select2'
import './features/select2-address.js'
import './features/sidebar'
import './features/address'

import './modules/dashboard.js'
import './modules/roles-drag'
import './modules/permissions-drag'
import './pages/household.js'
import './modules/modal.js'
import './pages/residents.js'
